#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Hypervisor Backend ABC — Strategy interface for Hyper-V / KVM / Mock."""
from abc import ABC, abstractmethod
from dataclasses import dataclass
from typing import Optional, Dict, Any, List, Tuple, Union


@dataclass(frozen=True)
class BackendResult:
    success: bool
    stdout: str
    stderr: str

# PSResult alias for backward compat
PSResult = BackendResult


class HypervisorBackend(ABC):
    @abstractmethod
    def check_available(self) -> bool: ...
    @abstractmethod
    def get_vm_status(self, vm_name: str) -> Optional[str]: ...
    @abstractmethod
    def get_vm_info(self, vm_name: str) -> Optional[Dict[str, Any]]: ...
    @abstractmethod
    def create_vm(self, vm_name: str, memory_mb: int, cpu_cores: int, vhd_path: Optional[str] = None, switch_name: Optional[str] = None, generation: int = 2) -> bool: ...
    @abstractmethod
    def start_vm(self, vm_name: str) -> bool: ...
    @abstractmethod
    def stop_vm(self, vm_name: str, force: bool = False) -> bool: ...
    @abstractmethod
    def remove_vm(self, vm_name: str, force: bool = True) -> bool: ...
    @abstractmethod
    def create_checkpoint(self, vm_name: str, checkpoint_name: str) -> bool: ...
    @abstractmethod
    def restore_checkpoint(self, vm_name: str, checkpoint_name: str) -> bool: ...
    @abstractmethod
    def create_differencing_disk(self, base_vhd: str, diff_vhd: str) -> bool: ...
    @abstractmethod
    def delete_file(self, path: str) -> bool: ...
    @abstractmethod
    def create_internal_switch(self, switch_name: str) -> bool: ...
    @abstractmethod
    def remove_switch(self, switch_name: str) -> bool: ...
    @abstractmethod
    def verify_host_integrity(self) -> Union[BackendResult, Tuple[bool, str]]: ...
    @abstractmethod
    def enable_guest_integration(self, vm_name: str) -> bool: ...
    @abstractmethod
    def execute_in_guest(self, vm_name: str, username: str, password: str, command: str, timeout: int = 30) -> BackendResult: ...
    @abstractmethod
    def configure_guest_firewall(self, vm_name: str, username: str, password: str, block_outbound: bool = True, allow_dns: bool = False) -> bool: ...
    @abstractmethod
    def test_guest_connectivity(self, vm_name: str, username: str, password: str, target: str = "8.8.8.8") -> bool: ...
    @abstractmethod
    def get_guest_processes(self, vm_name: str, username: str, password: str) -> List[Dict]: ...
    @abstractmethod
    def kill_guest_process(self, vm_name: str, username: str, password: str, process_name: str) -> bool: ...
    @abstractmethod
    def check_guest_vbs_status(self, vm_name: str, username: str, password: str) -> Dict[str, bool]: ...
    @abstractmethod
    def read_guest_event_log(self, vm_name: str, username: str, password: str, log_name: str = "Security", max_events: int = 50) -> List[Dict]: ...
    @abstractmethod
    def check_guest_registry(self, vm_name: str, username: str, password: str, key_path: str) -> List[Dict]: ...
    @abstractmethod
    def install_sysmon_in_guest(self, vm_name: str, username: str, password: str, sysmon_path: str = "C:\\Tools\\Sysmon64.exe") -> bool: ...
